language: java
jdk:
- oraclejdk8
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy
- "[[ $TRAVIS_TAG == v[0-9.]* ]] && mvn clean deploy -Prelease"
before_install:
- openssl aes-256-cbc -K $encrypted_cd5de7924124_key -iv $encrypted_cd5de7924124_iv
  -in maven_files.tar.enc -out maven_files.tar -d
- tar xvf maven_files.tar
- mv settings.xml ~/.m2/settings.xml
- gpg --import travis.gpg
script:
- mvn clean install
cache:
  directories:
  - "$HOME/.m2"
